apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  push:
    branches:
      - '**'

jobs:
  my-cbci-job:
    steps:
      - name: Run a CloudBees CI job
        uses: cloudbees-io/cbci-run-job@v2
        with:
          url: http://103.99.149.57:8080/job/DevOps
          username: logicfocus
          token: ${{ secrets.CBCI_TOKEN }}
          job-name: sampleclinic
          test-type: JUnit
          test-result-location: testReport
