apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:

  build:
    if: cloudbees.api.url == 'https://api.saas-preprod.beescloud.com' || cloudbees.api.url == 'https://api.cloudbees.io'
    permissions:
      scm-token-own: read
      id-token: write
    steps:
      - name: Git checkout
        uses: https://github.com/cloudbees-io/checkout@v1

      - name: Maven build
        uses: docker://maven:3.8.5
        run: |
          ./mvnw package
